### PR TITLE
Add guidance on how to secure status lists.

### PR DESCRIPTION
**Pull request by msporny**
This PR is an attempt to address issue #52 by adding guidance on how to secure the status list.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/118.html" title="Last updated on Jan 13, 2024, 8:30 PM UTC (be298ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/118/dbe2e53...be298ab.html" title="Last updated on Jan 13, 2024, 8:30 PM UTC (be298ab)">Diff</a>

### CODE REVIEW

**Review by iherman — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Review by David-Chadwick — APPROVED** [review]
It seems reasonable to require the same security mechanism for the status list as for the verifiable credential. But it is not mandated if there is a requirement to not do so.

**Comment by TallTed** [comment]
> [@David-Chadwick] It seems reasonable to require the same security mechanism for the status list as for the verifiable credential. But it is not mandated if there is a requirement to not do so.

I cannot figure out what your second sentence is trying to say.

**Review by brianorwhatever — APPROVED** [review]

**Review by KDean-GS1 — APPROVED** [review]

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-10-vcwg#section3-4) on 2024-01-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Add guidance on how to secure status lists. (pr vc-bitstring-status-list#118)

_See github pull request [vc-bitstring-status-list#118](https://github.com/w3c/vc-bitstring-status-list/pull/118)._




**Manu Sporny:** we should not mix and match the security mechanisms on the status list and the vcs that it contains.  
… they should all use the same mechanism e.g. JWT or data integrity.  

</details>

**Comment by msporny** [comment]
Normative, multiple reviews, no changes requested, no objections, merging.

**Pull request merged**
